// Generated by themes/omarchy/generate.py; do not edit.
// Source URLs, revisions, checksums and notices: themes/omarchy/sources.json.
use super::{OmarchyTheme, ThemePreset};

pub(super) const PALETTES: &[(&str, [u32; 8])] = &[
    (
        "omarchy-catppuccin",
        [
            0x1e1e2e, 0x313244, 0xcdd6f4, 0x585b70, 0x89b4fa, 0xa6e3a1, 0xf9e2af, 0xf38ba8,
        ],
    ),
    (
        "omarchy-catppuccin-latte",
        [
            0xeff1f5, 0xdce0e8, 0x4c4f69, 0xacb0be, 0x1e66f5, 0x40a02b, 0xdf8e1d, 0xd20f39,
        ],
    ),
    (
        "omarchy-community-aetheria",
        [
            0x0e091d, 0x0e1729, 0x14b9b5, 0xc53253, 0xbe3f50, 0xe20342, 0x7cd699, 0xc8e967,
        ],
    ),
    (
        "omarchy-community-all-hallow-s-eve",
        [
            0x000000, 0x141414, 0xffffff, 0x404040, 0x3387cc, 0x66cc33, 0xcc7833, 0xc83730,
        ],
    ),
    (
        "omarchy-community-amberbyte",
        [
            0x1b1112, 0x2c2223, 0xf2e8e8, 0x2b1818, 0xd66b6b, 0xc05a5a, 0xd66b6b, 0xb44a4a,
        ],
    ),
    (
        "omarchy-community-arc-blueberry",
        [
            0x111422, 0x1a1e33, 0xbcc1dc, 0x424761, 0x8eb0e6, 0x3cec85, 0xeacd61, 0xe35535,
        ],
    ),
    (
        "omarchy-community-archwave",
        [
            0x1a0d2e, 0x28193e, 0xd4a5ff, 0x543a6e, 0x8b9aff, 0x5ffbf1, 0xf9f871, 0xff6ec7,
        ],
    ),
    (
        "omarchy-community-artzen",
        [
            0x181c1f, 0x2a2d30, 0xfdf9f8, 0xb18d85, 0xb97670, 0x9f6769, 0xbb6d6c, 0x9b584d,
        ],
    ),
    (
        "omarchy-community-ash",
        [
            0x121212, 0x212121, 0xe0e0e0, 0x5a5a5a, 0x626262, 0x767676, 0x9e9e9e, 0x8a8a8a,
        ],
    ),
    (
        "omarchy-community-atelier",
        [
            0x22221b, 0x303029, 0xdcd9d6, 0x6c6b5a, 0x36a166, 0x7d9726, 0xa5980d, 0xba6236,
        ],
    ),
    (
        "omarchy-community-aura",
        [
            0x282a36, 0x44475a, 0xf8f8f2, 0x44475a, 0x8be9fd, 0x8be9fd, 0xcbc3e3, 0xffafcc,
        ],
    ),
    (
        "omarchy-community-ayaka",
        [
            0x000000, 0x121212, 0xe6e6e6, 0x404040, 0x6699ff, 0x66cc66, 0xffcc66, 0xe65c5c,
        ],
    ),
    (
        "omarchy-community-azure-glow",
        [
            0x0a0f1a, 0x161f2c, 0xa8dfff, 0x123247, 0x00aaff, 0x00e0b8, 0x33ccff, 0x0099cc,
        ],
    ),
    (
        "omarchy-community-batman",
        [
            0x1b1d1e, 0x262828, 0xa7a8a3, 0x6d6f6e, 0xfcef0c, 0xc8be46, 0xf3fd21, 0xe6db43,
        ],
    ),
    (
        "omarchy-community-batou",
        [
            0x121212, 0x1d1d1d, 0xa4a4a4, 0x383735, 0x605d5b, 0xa5a297, 0xc6c4b0, 0xe19e74,
        ],
    ),
    (
        "omarchy-community-bauhaus",
        [
            0x101318, 0x212429, 0xeaeff5, 0x3a3f4c, 0x8999aa, 0x789fa2, 0xe7a46f, 0xcb886d,
        ],
    ),
    (
        "omarchy-community-biscuit-de-mar-dark",
        [
            0x1a1515, 0x2d2424, 0xdcc9bc, 0x725a5a, 0xae3f82, 0x768f80, 0x959a6b, 0xf07342,
        ],
    ),
    (
        "omarchy-community-black-arch",
        [
            0x000000, 0x141414, 0xffffff, 0x262626, 0x989898, 0x8e8e8e, 0xb9b9b9, 0x646464,
        ],
    ),
    (
        "omarchy-community-black-gold",
        [
            0x0d0d0d, 0x1e1d1a, 0xebdbb2, 0x303531, 0x6e6a58, 0xa3850e, 0x4d574e, 0xd35f5f,
        ],
    ),
    (
        "omarchy-community-black-sand",
        [
            0x14181e, 0x1c2026, 0xced6e0, 0x525d6a, 0xced6e0, 0x89b39b, 0xc3b798, 0xbd8489,
        ],
    ),
    (
        "omarchy-community-black-turq",
        [
            0x0a0a0a, 0x191a1a, 0xc8dcdc, 0x322f3b, 0xadf0e9, 0x8fecd5, 0xa9d1d7, 0xd35f5f,
        ],
    ),
    (
        "omarchy-community-blue-ridge-dark",
        [
            0x1c2128, 0x2c3036, 0xe8e6e3, 0x4a5568, 0x6b8cae, 0x7ea67c, 0xd4af37, 0xcd9575,
        ],
    ),
    (
        "omarchy-community-bluedotrb",
        [
            0x161616, 0x272728, 0xf2f4f8, 0x484848, 0x4242b1, 0x4242b1, 0x25be6a, 0xee5396,
        ],
    ),
    (
        "omarchy-community-castle-on-a-lake",
        [
            0x060606, 0x1f1f1e, 0xf0d4e4, 0x626262, 0x9b6b9f, 0x80a070, 0xd4b060, 0xa06048,
        ],
    ),
    (
        "omarchy-community-catppuccin-mocha-dark",
        [
            0x010101, 0x111214, 0xcdd6f4, 0x585b70, 0x89b4fa, 0xa6e3a1, 0xf9e2af, 0xf38ba8,
        ],
    ),
    (
        "omarchy-community-cincinnati",
        [
            0x101b25, 0x1f3846, 0xdfe6e4, 0x748a9b, 0x3a82db, 0x5a6b45, 0xc9b77e, 0x9c6b63,
        ],
    ),
    (
        "omarchy-community-citrus-cynapse",
        [
            0x000000, 0x0b0b0b, 0x929292, 0x9bd46a, 0xc0df44, 0xda630d, 0x8dee0b, 0xf6000e,
        ],
    ),
    (
        "omarchy-community-city-783",
        [
            0x181a1f, 0x24272c, 0xb9bec6, 0x4b515b, 0xad2222, 0xdce0e6, 0x9e1a1a, 0xe53939,
        ],
    ),
    (
        "omarchy-community-cobalt2",
        [
            0x122738, 0x193549, 0xffffff, 0x0050a4, 0xffc600, 0x3ad900, 0xffc600, 0xff628c,
        ],
    ),
    (
        "omarchy-community-coffee",
        [
            0x1d150f, 0x2d2118, 0xf0e2d0, 0x8f7a67, 0xe0a15c, 0xcdb878, 0xffda92, 0xd78a6f,
        ],
    ),
    (
        "omarchy-community-coffee-latte",
        [
            0xe8e3c3, 0xd9d2b5, 0x2d1a1d, 0x76756f, 0x8e2d53, 0x345600, 0x636600, 0xa4405e,
        ],
    ),
    (
        "omarchy-community-commit",
        [
            0x0b0f14, 0x121a24, 0x7cffb2, 0x5c739b, 0x5af78e, 0x5af78e, 0xf3f99d, 0xff5c57,
        ],
    ),
    (
        "omarchy-community-cpunk",
        [
            0x040303, 0x181717, 0xffffff, 0x7f6e6e, 0xaaacac, 0xd1d2d1, 0xfef348, 0xf82a2a,
        ],
    ),
    (
        "omarchy-community-crimson-gold",
        [
            0x300808, 0x411010, 0xd8b22d, 0xaaaaaa, 0x9f831c, 0xffdd55, 0xb91c1c, 0xee3333,
        ],
    ),
    (
        "omarchy-community-darcula",
        [
            0x2b2b2b, 0x353637, 0xa9b7c6, 0x5c5c5c, 0x6897bb, 0x629755, 0xcc7832, 0xff6b68,
        ],
    ),
    (
        "omarchy-community-demon",
        [
            0x0f0f0f, 0x1f1e1d, 0xe0d4c2, 0x6b6867, 0x5c624b, 0x586259, 0xe24c00, 0xbb1c1c,
        ],
    ),
    (
        "omarchy-community-dos-moos",
        [
            0x131516, 0x252626, 0xf8ebe3, 0x3a4849, 0x819890, 0x819890, 0xf4e276, 0xf0334a,
        ],
    ),
    (
        "omarchy-community-dotrb",
        [
            0x121212, 0x242424, 0xf5f5f5, 0x949494, 0xb14242, 0xb14242, 0xf0be66, 0xd66e36,
        ],
    ),
    (
        "omarchy-community-drac",
        [
            0x101428, 0x222538, 0xf2f4f8, 0x555555, 0x50fa7b, 0x1e90ff, 0xf1fa8c, 0xff5555,
        ],
    ),
    (
        "omarchy-community-dracula",
        [
            0x282a36, 0x343746, 0xf8f8f2, 0x6272a4, 0x8be9fd, 0x50fa7b, 0xf1fa8c, 0xff5555,
        ],
    ),
    (
        "omarchy-community-eldritch",
        [
            0x212337, 0x313446, 0xebfafa, 0x21222c, 0x9071f4, 0x37f499, 0xe9f941, 0xf9515d,
        ],
    ),
    (
        "omarchy-community-event-horizon",
        [
            0x1c1e26, 0x2a2c33, 0xcbced0, 0x6f6f70, 0x26bbd9, 0x29d398, 0xfac29a, 0xe95678,
        ],
    ),
    (
        "omarchy-community-evergarden",
        [
            0x232a2e, 0x2e3639, 0xadc9bc, 0xadc9bc, 0xb3e6db, 0xcbe3b3, 0xf5d098, 0xf57f82,
        ],
    ),
    (
        "omarchy-community-felix",
        [
            0x000000, 0x121212, 0xe7e9ea, 0x626262, 0xff8852, 0xe7e9ea, 0x9e9e9e, 0x8a8a8a,
        ],
    ),
    (
        "omarchy-community-fireside",
        [
            0x0a1220, 0x111f37, 0xf0f2f5, 0x5a606b, 0xb8b8b6, 0x889889, 0xb8b5a2, 0xe06b58,
        ],
    ),
    (
        "omarchy-community-flat-dracula",
        [
            0x282a36, 0x383a45, 0xf8f8f2, 0x6272a4, 0xbd93f9, 0x50fa7b, 0xf1fa8c, 0xff5555,
        ],
    ),
    (
        "omarchy-community-flexoki-dark",
        [
            0x100f0f, 0x1f1e1d, 0xcecdc3, 0x6f6e69, 0x4385be, 0x66800b, 0xad8301, 0xaf3029,
        ],
    ),
    (
        "omarchy-community-forest-green",
        [
            0x0f1a14, 0x1b2a1f, 0xa8e6a1, 0x3a4a3d, 0x5fa9a8, 0x6bbf7a, 0xd7ba7d, 0xe06c75,
        ],
    ),
    (
        "omarchy-community-frost",
        [
            0x0a0f1c, 0x121b33, 0xd4d5d9, 0x51545e, 0x9bb0c2, 0x95a8b8, 0x9fadb8, 0x869aac,
        ],
    ),
    (
        "omarchy-community-fuchsblau",
        [
            0x1a2234, 0x232c44, 0xcdd6ee, 0x4e5784, 0x4dd6c8, 0x86c79c, 0xf0a060, 0xe89a8a,
        ],
    ),
    (
        "omarchy-community-futurism",
        [
            0x0a1428, 0x17294a, 0xf0f8ff, 0x53627a, 0xff40a3, 0x00bfff, 0x5076b2, 0xff40a3,
        ],
    ),
    (
        "omarchy-community-futurist",
        [
            0x0a1624, 0x173049, 0xdceaf2, 0x5e7a88, 0x3ec8d4, 0x6bcf7a, 0xf0b84a, 0xe07a62,
        ],
    ),
    (
        "omarchy-community-gand",
        [
            0x3a332a, 0x463e33, 0xf5ecd9, 0x968872, 0xd6a06b, 0x83baa1, 0xdab46b, 0xed806b,
        ],
    ),
    (
        "omarchy-community-ghost-pastel",
        [
            0x070506, 0x1a1919, 0xffffff, 0x836f79, 0x979fec, 0x648ed0, 0xe095b5, 0xb37580,
        ],
    ),
    (
        "omarchy-community-gold-rush",
        [
            0x121212, 0x212121, 0xd9d9d9, 0x805b10, 0xc9a227, 0xa47e1b, 0xfad643, 0xdbb42c,
        ],
    ),
    (
        "omarchy-community-golden-brown",
        [
            0x0f0b05, 0x1d170f, 0xc3a983, 0x57462c, 0xc3a983, 0xdec8a7, 0xdec8a7, 0xa88c62,
        ],
    ),
    (
        "omarchy-community-greek-noir",
        [
            0x171717, 0x252525, 0xccd0cf, 0x525252, 0xf25623, 0xf25623, 0x757864, 0xaeab94,
        ],
    ),
    (
        "omarchy-community-green-garden",
        [
            0x1d271f, 0x2c352a, 0xe4d8b4, 0x505b51, 0x65a0d9, 0x7e9c58, 0xd29c5a, 0xc45b5b,
        ],
    ),
    (
        "omarchy-community-gruvbox-material",
        [
            0x282828, 0x32302f, 0xd4be98, 0x928374, 0xe78a4e, 0xa9b665, 0xd8a657, 0xea6962,
        ],
    ),
    (
        "omarchy-community-harbor",
        [
            0xdfe4c4, 0xcfd5b7, 0x1c2d28, 0x7d8794, 0x5e81ac, 0x556753, 0xdc8164, 0xb14752,
        ],
    ),
    (
        "omarchy-community-harbor-dark",
        [
            0x1b1b1b, 0x2b2b2a, 0xefebdc, 0x817f68, 0xe75a50, 0xe75a50, 0xa99b7a, 0xf44336,
        ],
    ),
    (
        "omarchy-community-hermarchy",
        [
            0x08090a, 0x101214, 0xf1f1ec, 0x606468, 0x61d6ff, 0x86d993, 0xe2c275, 0xe46e6e,
        ],
    ),
    (
        "omarchy-community-hinterlands",
        [
            0x222222, 0x333333, 0xffffff, 0x525252, 0x686868, 0x8b8b8b, 0xa0a0a0, 0x7c7c7c,
        ],
    ),
    (
        "omarchy-community-infernium",
        [
            0x1c1c1c, 0x2b2b2b, 0xe0e0e0, 0x767476, 0xaeb1c0, 0x767476, 0xf7d383, 0xd66938,
        ],
    ),
    (
        "omarchy-community-inky-pinky",
        [
            0x13131d, 0x21212a, 0xc8c8c8, 0x434353, 0x7c7ca8, 0xa6b2c7, 0xd18ba2, 0xea90a8,
        ],
    ),
    (
        "omarchy-community-japan-night",
        [
            0x0b1b2b, 0x11304e, 0xb9b6a7, 0x294857, 0x2b5e8f, 0x708c8b, 0x7b8768, 0xb9968f,
        ],
    ),
    (
        "omarchy-community-lamplight",
        [
            0x151515, 0x1e1e1e, 0xe7e7e7, 0x7a7a75, 0xd97757, 0x78bd74, 0xc68f32, 0xd76563,
        ],
    ),
    (
        "omarchy-community-lawson-night",
        [
            0x1e1e2e, 0x353543, 0xcdd6f4, 0x45475a, 0x89b4fa, 0xa6e3a1, 0xf9e2af, 0xf38ba8,
        ],
    ),
    (
        "omarchy-community-map-quest",
        [
            0xecd3a1, 0xddc799, 0x3c4747, 0xb79f70, 0x1c2121, 0x3a443d, 0x826e48, 0x4f351e,
        ],
    ),
    (
        "omarchy-community-mars",
        [
            0x000000, 0x110e0d, 0xd9afa7, 0x4a2c2c, 0x7b534e, 0x7b534e, 0xc45a3f, 0xe07b5f,
        ],
    ),
    (
        "omarchy-community-matrix",
        [
            0x080c09, 0x121a13, 0x8bc98c, 0x678d6a, 0x3cbf5c, 0x2d9a48, 0xb8ba48, 0xd15d57,
        ],
    ),
    (
        "omarchy-community-mechanoonna",
        [
            0x1c1b19, 0x2c2b26, 0xf0e4c5, 0x6b655c, 0xd4bd99, 0xa89984, 0xebdbb2, 0xc5564a,
        ],
    ),
    (
        "omarchy-community-midnight",
        [
            0x000000, 0x121212, 0xefefef, 0x1e1e1e, 0x407e70, 0x8a9a7b, 0xffc107, 0xd35f5f,
        ],
    ),
    (
        "omarchy-community-milky-matcha",
        [
            0xf4f1e8, 0xe7e6dc, 0x5c6a53, 0xd6ccb9, 0x7a92a5, 0x7a9461, 0xd4a574, 0xc65f5f,
        ],
    ),
    (
        "omarchy-community-mini-jcw",
        [
            0x0b0b0d, 0x1a1a1c, 0xd8d8da, 0x3c3c40, 0xc8102e, 0x2f6b4f, 0xc9a227, 0xc8102e,
        ],
    ),
    (
        "omarchy-community-monochrome",
        [
            0x282828, 0x353535, 0xd4d4d4, 0x767676, 0xd4d4d4, 0xd4d4d4, 0xd4d4d4, 0xd4d4d4,
        ],
    ),
    (
        "omarchy-community-monokai",
        [
            0x0a1220, 0x111f37, 0xf0f2f5, 0x555c65, 0x78dce8, 0xb2d977, 0xf2c063, 0xf25e86,
        ],
    ),
    (
        "omarchy-community-moodpeak",
        [
            0x181c22, 0x282c32, 0xe0e6ed, 0x3d4455, 0x4ecdc4, 0x4ecdc4, 0x82eeff, 0xff7b92,
        ],
    ),
    (
        "omarchy-community-nagai-poolside",
        [
            0x0f1b22, 0x202c32, 0xe6f1f4, 0x2a4652, 0x2295d9, 0x7ca348, 0xeed59a, 0xff6b6b,
        ],
    ),
    (
        "omarchy-community-naysayer",
        [
            0x072626, 0x0a3434, 0xd3b58d, 0x504038, 0xadd8e6, 0x90ee90, 0x8fbc8f, 0x800000,
        ],
    ),
    (
        "omarchy-community-neo-sploosh",
        [
            0x212226, 0x313236, 0xf4f4f4, 0x595959, 0x008dc9, 0x92bf38, 0xa4d149, 0x893151,
        ],
    ),
    (
        "omarchy-community-neon-dusk",
        [
            0x16122a, 0x221b3c, 0xcfc7e8, 0x3a3154, 0xe85faf, 0x4be09a, 0xeec06a, 0xf2596c,
        ],
    ),
    (
        "omarchy-community-neovoid",
        [
            0x000000, 0x111111, 0xe0e0e0, 0x1a1a1a, 0x00bfff, 0x00bfff, 0x1e90ff, 0xff0040,
        ],
    ),
    (
        "omarchy-community-neptune-blue",
        [
            0x0b1012, 0x1a252a, 0xc8d0d4, 0x3a4e56, 0x6a8f9a, 0x4a7a68, 0xc4a86a, 0xc45a4a,
        ],
    ),
    (
        "omarchy-community-nes",
        [
            0x101010, 0x1f1f1f, 0xcecfc9, 0x525351, 0x9a9d9a, 0x9a9d9a, 0x9a9d9a, 0xd93f37,
        ],
    ),
    (
        "omarchy-community-noir",
        [
            0x000000, 0x0f0f0f, 0xc1c1c1, 0x505050, 0x8a9a7b, 0xc1c1c1, 0x888888, 0x8a9a7b,
        ],
    ),
    (
        "omarchy-community-nujabes",
        [
            0x0d0a11, 0x231a2b, 0xe3dcda, 0x6b5268, 0xb26ac6, 0x9aa06b, 0xe0c25a, 0xc56e6f,
        ],
    ),
    (
        "omarchy-community-oligarchy",
        [
            0x0b1020, 0x141e30, 0xe8eef6, 0x65718a, 0xc6f36b, 0x9fe870, 0xf4c95d, 0xff6b6b,
        ],
    ),
    (
        "omarchy-community-omacarchy",
        [
            0x1c1c1e, 0x2e2e30, 0xffffff, 0x2c2c2e, 0x7a7a7a, 0x5a5a5a, 0x6a6a6a, 0x4a4a4a,
        ],
    ),
    (
        "omarchy-community-omaled",
        [
            0x000000, 0x5a000b, 0xe66063, 0x5a000b, 0x860111, 0xbd1f21, 0xe66063, 0xdd2c2f,
        ],
    ),
    (
        "omarchy-community-one-dark",
        [
            0x282c34, 0x333842, 0xabb2bf, 0x5c6370, 0x61afef, 0x98c379, 0xe5c07b, 0xe06c75,
        ],
    ),
    (
        "omarchy-community-one-dark-pro",
        [
            0x282c34, 0x3e4451, 0xabb2bf, 0x5c6370, 0x61afef, 0x98c379, 0xe5c07b, 0xe06c75,
        ],
    ),
    (
        "omarchy-community-oxo-carbon",
        [
            0x161616, 0x272728, 0xf2f4f8, 0x525252, 0x33b1ff, 0x33b1ff, 0xee5396, 0x3ddbd9,
        ],
    ),
    (
        "omarchy-community-pagan",
        [
            0x0a0a0a, 0x0f0f0f, 0xf2f2f2, 0x6e6e6e, 0x25aff4, 0x63aa87, 0xc9ae6d, 0xde443e,
        ],
    ),
    (
        "omarchy-community-pandora",
        [
            0x0a0a0c, 0x171719, 0xb2b5b3, 0x363638, 0x7aa2f7, 0x9ece6a, 0xe0af68, 0xf7768e,
        ],
    ),
    (
        "omarchy-community-periphery",
        [
            0x060f12, 0x0f2129, 0xa9c0bf, 0x5c7876, 0x7fc9c4, 0x7fae8e, 0xc9a06a, 0xd4644a,
        ],
    ),
    (
        "omarchy-community-pina",
        [
            0x171a18, 0x252a27, 0xd4d5d5, 0x595b5a, 0x7dd2b8, 0xb8c082, 0xe0d480, 0xd47c6b,
        ],
    ),
    (
        "omarchy-community-pink-blood",
        [
            0x050007, 0x170a12, 0xf17e97, 0xa85869, 0xe80f3e, 0xaf0b39, 0xce0d3c, 0x8f0936,
        ],
    ),
    (
        "omarchy-community-pulsar",
        [
            0x0a0314, 0x1c0a2c, 0xe0e6ff, 0xaa5abc, 0x3298fa, 0x5cb960, 0xf2e42e, 0xe53e61,
        ],
    ),
    (
        "omarchy-community-purple-moon",
        [
            0x020007, 0x16141a, 0xffffff, 0x9c6cd0, 0x9b49c8, 0x643aad, 0x9845c6, 0x37277d,
        ],
    ),
    (
        "omarchy-community-purplewave",
        [
            0x121212, 0x211e20, 0xd7accd, 0xff9acb, 0xd7accd, 0x8673d4, 0xca2edc, 0xff4da6,
        ],
    ),
    (
        "omarchy-community-quattrocento-light",
        [
            0xf0e6d3, 0xe9dfc9, 0x33291b, 0x8a7a5e, 0x8a4a2c, 0x3f6b4a, 0x7d5a10, 0xa32d2a,
        ],
    ),
    (
        "omarchy-community-rainy-night",
        [
            0x1e1e2e, 0x2c2c3d, 0xcdd6f4, 0x585b70, 0x89b4fa, 0xa6e3a1, 0xf9e2af, 0xf38ba8,
        ],
    ),
    (
        "omarchy-community-red-monarch",
        [
            0x191414, 0x2b2525, 0xffeaf2, 0x2a2025, 0xf1396d, 0xd93665, 0xffb3ca, 0xf1396d,
        ],
    ),
    (
        "omarchy-community-red-pill",
        [
            0x050b07, 0x0b170f, 0xc8f5d4, 0x2c5138, 0xf7931a, 0x00d94a, 0xf7c948, 0xff4d2e,
        ],
    ),
    (
        "omarchy-community-retropc",
        [
            0x0a0a08, 0x1d1707, 0xffb000, 0x805500, 0xcc9900, 0xffcc00, 0xffd700, 0xff8800,
        ],
    ),
    (
        "omarchy-community-ristretto-light",
        [
            0xfdf6ee, 0xebe4dd, 0x22211d, 0xa09080, 0x85b34c, 0x29472a, 0x8a6c3e, 0xdf2b0d,
        ],
    ),
    (
        "omarchy-community-robzee84",
        [
            0x000000, 0x141414, 0xffffff, 0x495495, 0xff7edb, 0x72f1b8, 0xf3e70f, 0xfe4450,
        ],
    ),
    (
        "omarchy-community-rose-of-dune",
        [
            0xf5e6d3, 0xe5d7c5, 0x35302a, 0xc8ac86, 0x76634c, 0x9e4f5b, 0x644535, 0xa02b16,
        ],
    ),
    (
        "omarchy-community-rose-pine-dark",
        [
            0x191724, 0x26233a, 0xe0def4, 0x6e6a86, 0xebbcba, 0x31748f, 0xf6c177, 0xeb6f92,
        ],
    ),
    (
        "omarchy-community-rose-pine-moon",
        [
            0x232136, 0x393552, 0xe0def4, 0x56526e, 0x9ccfd8, 0x3e8fb0, 0xf6c177, 0xeb6f92,
        ],
    ),
    (
        "omarchy-community-ryu",
        [
            0x050505, 0x151514, 0xd6d0c5, 0x404040, 0x525e5a, 0x8b9388, 0x51605b, 0xda614e,
        ],
    ),
    (
        "omarchy-community-saga",
        [
            0x05080a, 0x191b1d, 0xfff6ff, 0x4b4c4d, 0xb2fff3, 0xbaf7b5, 0xfff6c3, 0xff9fbc,
        ],
    ),
    (
        "omarchy-community-sakura",
        [
            0x0d0509, 0x230e18, 0xf0eaed, 0x7a5c66, 0xd9a56c, 0xf29b9a, 0xd4a882, 0xe85f6f,
        ],
    ),
    (
        "omarchy-community-sakura-mochi",
        [
            0x0b0d11, 0x1d1a1f, 0xf0b7ca, 0x678270, 0xf23888, 0x5aa15d, 0xd7be96, 0xf23888,
        ],
    ),
    (
        "omarchy-community-sapphire",
        [
            0x060d1f, 0x171f30, 0xe0f7fa, 0x51688e, 0xf7c3c6, 0x6488ea, 0xd5edeb, 0xe95c4b,
        ],
    ),
    (
        "omarchy-community-shades-of-jade",
        [
            0x00110b, 0x12231d, 0xe6f6f0, 0x3e6650, 0xd1ffb0, 0x00a86b, 0xd1ffb0, 0xff3370,
        ],
    ),
    (
        "omarchy-community-snow",
        [
            0xffffff, 0xf7f7f7, 0x0a0a0a, 0x919191, 0x0a0a0a, 0x0a0a0a, 0x0a0a0a, 0x0a0a0a,
        ],
    ),
    (
        "omarchy-community-snow-black",
        [
            0x000000, 0x141414, 0xffffff, 0x333333, 0x888888, 0xdd9999, 0xa06666, 0x5f8787,
        ],
    ),
    (
        "omarchy-community-solarized",
        [
            0x002b36, 0x0a333d, 0x839496, 0x002b36, 0x268bd2, 0x859900, 0xb58900, 0xdc322f,
        ],
    ),
    (
        "omarchy-community-solarized-light",
        [
            0xfdf6e3, 0xefebda, 0x586e75, 0x002b36, 0x268bd2, 0x859900, 0xb58900, 0xdc322f,
        ],
    ),
    (
        "omarchy-community-solarized-osaka",
        [
            0x001c2b, 0x082331, 0x6c7c81, 0x5f6f74, 0x268bd2, 0x809900, 0xb38800, 0xd8322f,
        ],
    ),
    (
        "omarchy-community-space-monkey",
        [
            0x1c0e00, 0x291603, 0xe7aa5a, 0x948a8b, 0xbd4924, 0xdf782d, 0xf9cc6c, 0xfd6883,
        ],
    ),
    (
        "omarchy-community-starry-night",
        [
            0x000519, 0x05152c, 0xd1dad3, 0x4e5d70, 0xbaba00, 0x56ca9c, 0xa2b23d, 0xa2b238,
        ],
    ),
    (
        "omarchy-community-starsend",
        [
            0x05090a, 0x0e1719, 0xc3d2d0, 0x617877, 0xf0913f, 0x86a68f, 0xc9a878, 0xd2705c,
        ],
    ),
    (
        "omarchy-community-sunset",
        [
            0x070605, 0x1a1919, 0xffffff, 0x969596, 0xd0b59b, 0xf7ce6e, 0xb2a295, 0xdda660,
        ],
    ),
    (
        "omarchy-community-sunset-drive",
        [
            0x0f0f19, 0x20202b, 0xededfe, 0x181824, 0x33a1ff, 0x00f59b, 0xffea00, 0xff3366,
        ],
    ),
    (
        "omarchy-community-super-game-bro",
        [
            0x214130, 0x29492f, 0x88a827, 0x416828, 0x88a827, 0x88a827, 0x699020, 0x88a827,
        ],
    ),
    (
        "omarchy-community-synthwave-84",
        [
            0x240037, 0x351447, 0xffffff, 0x614d85, 0x0080ff, 0x8f00ff, 0xf3e70f, 0xff0040,
        ],
    ),
    (
        "omarchy-community-temerald",
        [
            0x121111, 0x222322, 0xdcfce7, 0x6b6b6b, 0x93c5fd, 0x4ade7f, 0xd4953b, 0xd35f5f,
        ],
    ),
    (
        "omarchy-community-terminus",
        [
            0x0c1626, 0x17243a, 0xd8cbb4, 0x5e6e87, 0xd9a862, 0x93b56f, 0xd9a862, 0xdb684c,
        ],
    ),
    (
        "omarchy-community-the-greek",
        [
            0xd0d0c8, 0xc2c2ba, 0x242424, 0x6b7360, 0xde6a41, 0x2e3125, 0x51573b, 0xdb0030,
        ],
    ),
    (
        "omarchy-community-tokyo-night-oled",
        [
            0x000000, 0x0d0e11, 0xa9b1d6, 0x444b6a, 0x7aa2f7, 0x9ece6a, 0xe0af68, 0xf7768e,
        ],
    ),
    (
        "omarchy-community-tycho",
        [
            0x1e2125, 0x2e3134, 0xf0e9ec, 0x897981, 0x9b826b, 0xb4756b, 0xc17a6a, 0x976870,
        ],
    ),
    (
        "omarchy-community-van-gogh",
        [
            0x0a192f, 0x1c3a5e, 0xf2e2a4, 0x2c4668, 0xe6b422, 0x7fb3d5, 0xf2e2a4, 0xd9822b,
        ],
    ),
    (
        "omarchy-community-vault",
        [
            0x191510, 0x272018, 0xd3c0a8, 0x867658, 0xe09355, 0x9cba64, 0xd9ab5e, 0xdb6c4f,
        ],
    ),
    (
        "omarchy-community-velvet-night",
        [
            0x0a101f, 0x1d2330, 0xffffff, 0x6b72a8, 0x9099a5, 0x5c637a, 0xe5af1b, 0x811139,
        ],
    ),
    (
        "omarchy-community-venice-from-above",
        [
            0xf5f2e9, 0xf6f3eb, 0x492924, 0x85837d, 0x72684b, 0x6f6644, 0x6f6645, 0x706548,
        ],
    ),
    (
        "omarchy-community-vesper",
        [
            0x101010, 0x232323, 0xffffff, 0x7e7e7e, 0xaca1cf, 0x90b99f, 0xe6b99d, 0xf5a191,
        ],
    ),
    (
        "omarchy-community-vhs-80",
        [
            0x121212, 0x212121, 0xd4d4d4, 0x8a8a8d, 0x862020, 0x277d46, 0xa85511, 0x862020,
        ],
    ),
    (
        "omarchy-community-void",
        [
            0x05010c, 0x19151f, 0xffffff, 0x6b578f, 0xbb9af7, 0xc2b8ff, 0xddccff, 0xf07178,
        ],
    ),
    (
        "omarchy-community-vulkanite",
        [
            0x0f1416, 0x151b1e, 0xdce5e9, 0x8e969a, 0x8fe0fa, 0x8be086, 0xe0af68, 0xe05f64,
        ],
    ),
    (
        "omarchy-community-waffle-cat",
        [
            0x292025, 0x3a3033, 0xfff4d8, 0xa58c82, 0xc87d2a, 0x9fad68, 0xc8964b, 0xcf7358,
        ],
    ),
    (
        "omarchy-community-waveform-dark",
        [
            0x0a0a0a, 0x1d1515, 0xff9999, 0x4a2020, 0xcc00ff, 0xff6600, 0xffaa00, 0xff3333,
        ],
    ),
    (
        "omarchy-community-white-gold",
        [
            0xdedbc8, 0xcdcab9, 0x0c0c14, 0x9a9078, 0x005c32, 0x725c0a, 0x2e311a, 0x4b0304,
        ],
    ),
    (
        "omarchy-community-windows-dark-mode",
        [
            0x181818, 0x2a2a2a, 0xffffff, 0x616161, 0x0078d4, 0x2ea043, 0xbb8009, 0xf85149,
        ],
    ),
    (
        "omarchy-community-winslow",
        [
            0x13201b, 0x2b3632, 0xd6c9b1, 0x616865, 0x9ba4bb, 0x6f806d, 0x9d917a, 0x85795f,
        ],
    ),
    (
        "omarchy-ethereal",
        [
            0x060b1e, 0x131a3a, 0xffcead, 0x6d7db6, 0x7d82d9, 0x92a593, 0xe9bb4f, 0xed5b5a,
        ],
    ),
    (
        "omarchy-everforest",
        [
            0x2d353b, 0x343f44, 0xd3c6aa, 0x475258, 0x7fbbb3, 0xa7c080, 0xdbbc7f, 0xe67e80,
        ],
    ),
    (
        "omarchy-flexoki-light",
        [
            0xfffcf0, 0xe6e4d9, 0x100f0f, 0xb7b5ac, 0x205ea6, 0x879a39, 0xd0a215, 0xd14d41,
        ],
    ),
    (
        "omarchy-gruvbox",
        [
            0x282828, 0x3c3836, 0xd4be98, 0x665c54, 0x7daea3, 0xa9b665, 0xd8a657, 0xea6962,
        ],
    ),
    (
        "omarchy-hackerman",
        [
            0x0b0c16, 0x151828, 0xddf7ff, 0x2d3450, 0x82fb9c, 0x4fe88f, 0x50f7d4, 0x50f872,
        ],
    ),
    (
        "omarchy-kanagawa",
        [
            0x1f1f28, 0x223249, 0xdcd7ba, 0x54546d, 0xdcd7ba, 0x76946a, 0xc0a36e, 0xc34043,
        ],
    ),
    (
        "omarchy-last-horizon",
        [
            0x0c0b0c, 0x0c0b0c, 0xfafcfb, 0x584e51, 0xb59790, 0x87a9b0, 0x6b5e73, 0xc38b7b,
        ],
    ),
    (
        "omarchy-local-aamis",
        [
            0x0f0f0f, 0x201f1e, 0xeadccc, 0x706a6a, 0xe2be8a, 0xcea37f, 0xf4bb54, 0xe25d6c,
        ],
    ),
    (
        "omarchy-local-arc-raiders",
        [
            0x0c060d, 0x1f191f, 0xfafafa, 0x8e8787, 0x3f57a1, 0xb0413b, 0xdca23e, 0x6a5457,
        ],
    ),
    (
        "omarchy-local-ash",
        [
            0x121212, 0x212121, 0xe0e0e0, 0x5a5a5a, 0x626262, 0x767676, 0x9e9e9e, 0x8a8a8a,
        ],
    ),
    (
        "omarchy-local-boring",
        [
            0x000000, 0x0d0e11, 0xa9b1d6, 0x444b6a, 0x7aa2f7, 0x9ece6a, 0xe0af68, 0xf7768e,
        ],
    ),
    (
        "omarchy-local-dos-moos",
        [
            0x131516, 0x252626, 0xf8ebe3, 0x3a4849, 0x819890, 0x819890, 0xf4e276, 0xf0334a,
        ],
    ),
    (
        "omarchy-local-felix",
        [
            0x000000, 0x121212, 0xe7e9ea, 0x626262, 0xff8852, 0xe7e9ea, 0x9e9e9e, 0x8a8a8a,
        ],
    ),
    (
        "omarchy-local-flexoki-dark",
        [
            0x100f0f, 0x1f1e1d, 0xcecdc3, 0x6f6e69, 0x4385be, 0x66800b, 0xad8301, 0xaf3029,
        ],
    ),
    (
        "omarchy-local-ibm",
        [
            0x050709, 0x191a1c, 0xffffff, 0x4a4a4a, 0x727272, 0xd24646, 0xb4b47b, 0x66a773,
        ],
    ),
    (
        "omarchy-local-koyanagi",
        [
            0x1c1c1e, 0x2c2c2e, 0xf2f2f2, 0x6a6a6a, 0xffdd80, 0xf2f2f2, 0xffdd80, 0xf2f2f2,
        ],
    ),
    (
        "omarchy-local-midnight",
        [
            0x000000, 0x121212, 0xefefef, 0x1e1e1e, 0x407e70, 0x8a9a7b, 0xffc107, 0xd35f5f,
        ],
    ),
    (
        "omarchy-local-minimal",
        [
            0x000000, 0x121212, 0xe7e9ea, 0x626262, 0xd3d3d3, 0xe7e9ea, 0x9e9e9e, 0x8a8a8a,
        ],
    ),
    (
        "omarchy-lumon",
        [
            0x16242d, 0x1b2d40, 0xd6e2ee, 0x304860, 0x8bc9eb, 0x5e95bc, 0x6fa4c9, 0x4d86b0,
        ],
    ),
    (
        "omarchy-lupine",
        [
            0xfafafa, 0xf5f5f5, 0x212121, 0x9e9e9e, 0x3264eb, 0x4a2fd0, 0x026fde, 0xc900c4,
        ],
    ),
    (
        "omarchy-matte-black",
        [
            0x121212, 0x1e1e1e, 0xbebebe, 0x333333, 0xe68e0d, 0xffc107, 0xb91c1c, 0xd35f5f,
        ],
    ),
    (
        "omarchy-miasma",
        [
            0x222222, 0x2c2c2c, 0xc2c2b0, 0x666666, 0x78824b, 0x5f875f, 0xb36d43, 0x685742,
        ],
    ),
    (
        "omarchy-nord",
        [
            0x2e3440, 0x3b4252, 0xd8dee9, 0x4c566a, 0x81a1c1, 0xa3be8c, 0xebcb8b, 0xbf616a,
        ],
    ),
    (
        "omarchy-osaka-jade",
        [
            0x111c18, 0x23372b, 0xc1c497, 0x53685b, 0x509475, 0x549e6a, 0x459451, 0xff5345,
        ],
    ),
    (
        "omarchy-retro-82",
        [
            0x05182e, 0x0a2540, 0xf6dcac, 0x2a6b78, 0xfaa968, 0x028391, 0xe97b3c, 0xf85525,
        ],
    ),
    (
        "omarchy-ristretto",
        [
            0x2c2525, 0x3d2f2a, 0xe6d9db, 0x72696a, 0xf38d70, 0xadda78, 0xf9cc6c, 0xfd6883,
        ],
    ),
    (
        "omarchy-rose-pine",
        [
            0xfaf4ed, 0xf2e9e1, 0x575279, 0xcecacd, 0x56949f, 0x286983, 0xea9d34, 0xb4637a,
        ],
    ),
    (
        "omarchy-solitude",
        [
            0x101315, 0x101315, 0xcacccc, 0x4b4e55, 0x798186, 0x9fa5a9, 0xd9dbdc, 0x565d60,
        ],
    ),
    (
        "omarchy-tokyo-night",
        [
            0x1a1b26, 0x24283b, 0xa9b1d6, 0x414868, 0x7aa2f7, 0x9ece6a, 0xe0af68, 0xf7768e,
        ],
    ),
    (
        "omarchy-vantablack",
        [
            0x000000, 0x1a1a1a, 0xffffff, 0x7a7a7a, 0x8d8d8d, 0xb6b6b6, 0xcecece, 0xa4a4a4,
        ],
    ),
    (
        "omarchy-white",
        [
            0xffffff, 0xc0c0c0, 0x000000, 0x808080, 0x6e6e6e, 0x3a3a3a, 0x4a4a4a, 0x2a2a2a,
        ],
    ),
];

pub(super) const ALL: &[ThemePreset] = &[
    ThemePreset::UnitermDark,
    ThemePreset::UnitermLight,
    ThemePreset::Catppuccin,
    ThemePreset::TokyoNight,
    ThemePreset::Dracula,
    ThemePreset::Nord,
    ThemePreset::GruvboxDark,
    ThemePreset::GruvboxLight,
    ThemePreset::SolarizedDark,
    ThemePreset::SolarizedLight,
    ThemePreset::Kanagawa,
    ThemePreset::RosePine,
    ThemePreset::Omarchy(OmarchyTheme(0)),
    ThemePreset::Omarchy(OmarchyTheme(1)),
    ThemePreset::Omarchy(OmarchyTheme(2)),
    ThemePreset::Omarchy(OmarchyTheme(3)),
    ThemePreset::Omarchy(OmarchyTheme(4)),
    ThemePreset::Omarchy(OmarchyTheme(5)),
    ThemePreset::Omarchy(OmarchyTheme(6)),
    ThemePreset::Omarchy(OmarchyTheme(7)),
    ThemePreset::Omarchy(OmarchyTheme(8)),
    ThemePreset::Omarchy(OmarchyTheme(9)),
    ThemePreset::Omarchy(OmarchyTheme(10)),
    ThemePreset::Omarchy(OmarchyTheme(11)),
    ThemePreset::Omarchy(OmarchyTheme(12)),
    ThemePreset::Omarchy(OmarchyTheme(13)),
    ThemePreset::Omarchy(OmarchyTheme(14)),
    ThemePreset::Omarchy(OmarchyTheme(15)),
    ThemePreset::Omarchy(OmarchyTheme(16)),
    ThemePreset::Omarchy(OmarchyTheme(17)),
    ThemePreset::Omarchy(OmarchyTheme(18)),
    ThemePreset::Omarchy(OmarchyTheme(19)),
    ThemePreset::Omarchy(OmarchyTheme(20)),
    ThemePreset::Omarchy(OmarchyTheme(21)),
    ThemePreset::Omarchy(OmarchyTheme(22)),
    ThemePreset::Omarchy(OmarchyTheme(23)),
    ThemePreset::Omarchy(OmarchyTheme(24)),
    ThemePreset::Omarchy(OmarchyTheme(25)),
    ThemePreset::Omarchy(OmarchyTheme(26)),
    ThemePreset::Omarchy(OmarchyTheme(27)),
    ThemePreset::Omarchy(OmarchyTheme(28)),
    ThemePreset::Omarchy(OmarchyTheme(29)),
    ThemePreset::Omarchy(OmarchyTheme(30)),
    ThemePreset::Omarchy(OmarchyTheme(31)),
    ThemePreset::Omarchy(OmarchyTheme(32)),
    ThemePreset::Omarchy(OmarchyTheme(33)),
    ThemePreset::Omarchy(OmarchyTheme(34)),
    ThemePreset::Omarchy(OmarchyTheme(35)),
    ThemePreset::Omarchy(OmarchyTheme(36)),
    ThemePreset::Omarchy(OmarchyTheme(37)),
    ThemePreset::Omarchy(OmarchyTheme(38)),
    ThemePreset::Omarchy(OmarchyTheme(39)),
    ThemePreset::Omarchy(OmarchyTheme(40)),
    ThemePreset::Omarchy(OmarchyTheme(41)),
    ThemePreset::Omarchy(OmarchyTheme(42)),
    ThemePreset::Omarchy(OmarchyTheme(43)),
    ThemePreset::Omarchy(OmarchyTheme(44)),
    ThemePreset::Omarchy(OmarchyTheme(45)),
    ThemePreset::Omarchy(OmarchyTheme(46)),
    ThemePreset::Omarchy(OmarchyTheme(47)),
    ThemePreset::Omarchy(OmarchyTheme(48)),
    ThemePreset::Omarchy(OmarchyTheme(49)),
    ThemePreset::Omarchy(OmarchyTheme(50)),
    ThemePreset::Omarchy(OmarchyTheme(51)),
    ThemePreset::Omarchy(OmarchyTheme(52)),
    ThemePreset::Omarchy(OmarchyTheme(53)),
    ThemePreset::Omarchy(OmarchyTheme(54)),
    ThemePreset::Omarchy(OmarchyTheme(55)),
    ThemePreset::Omarchy(OmarchyTheme(56)),
    ThemePreset::Omarchy(OmarchyTheme(57)),
    ThemePreset::Omarchy(OmarchyTheme(58)),
    ThemePreset::Omarchy(OmarchyTheme(59)),
    ThemePreset::Omarchy(OmarchyTheme(60)),
    ThemePreset::Omarchy(OmarchyTheme(61)),
    ThemePreset::Omarchy(OmarchyTheme(62)),
    ThemePreset::Omarchy(OmarchyTheme(63)),
    ThemePreset::Omarchy(OmarchyTheme(64)),
    ThemePreset::Omarchy(OmarchyTheme(65)),
    ThemePreset::Omarchy(OmarchyTheme(66)),
    ThemePreset::Omarchy(OmarchyTheme(67)),
    ThemePreset::Omarchy(OmarchyTheme(68)),
    ThemePreset::Omarchy(OmarchyTheme(69)),
    ThemePreset::Omarchy(OmarchyTheme(70)),
    ThemePreset::Omarchy(OmarchyTheme(71)),
    ThemePreset::Omarchy(OmarchyTheme(72)),
    ThemePreset::Omarchy(OmarchyTheme(73)),
    ThemePreset::Omarchy(OmarchyTheme(74)),
    ThemePreset::Omarchy(OmarchyTheme(75)),
    ThemePreset::Omarchy(OmarchyTheme(76)),
    ThemePreset::Omarchy(OmarchyTheme(77)),
    ThemePreset::Omarchy(OmarchyTheme(78)),
    ThemePreset::Omarchy(OmarchyTheme(79)),
    ThemePreset::Omarchy(OmarchyTheme(80)),
    ThemePreset::Omarchy(OmarchyTheme(81)),
    ThemePreset::Omarchy(OmarchyTheme(82)),
    ThemePreset::Omarchy(OmarchyTheme(83)),
    ThemePreset::Omarchy(OmarchyTheme(84)),
    ThemePreset::Omarchy(OmarchyTheme(85)),
    ThemePreset::Omarchy(OmarchyTheme(86)),
    ThemePreset::Omarchy(OmarchyTheme(87)),
    ThemePreset::Omarchy(OmarchyTheme(88)),
    ThemePreset::Omarchy(OmarchyTheme(89)),
    ThemePreset::Omarchy(OmarchyTheme(90)),
    ThemePreset::Omarchy(OmarchyTheme(91)),
    ThemePreset::Omarchy(OmarchyTheme(92)),
    ThemePreset::Omarchy(OmarchyTheme(93)),
    ThemePreset::Omarchy(OmarchyTheme(94)),
    ThemePreset::Omarchy(OmarchyTheme(95)),
    ThemePreset::Omarchy(OmarchyTheme(96)),
    ThemePreset::Omarchy(OmarchyTheme(97)),
    ThemePreset::Omarchy(OmarchyTheme(98)),
    ThemePreset::Omarchy(OmarchyTheme(99)),
    ThemePreset::Omarchy(OmarchyTheme(100)),
    ThemePreset::Omarchy(OmarchyTheme(101)),
    ThemePreset::Omarchy(OmarchyTheme(102)),
    ThemePreset::Omarchy(OmarchyTheme(103)),
    ThemePreset::Omarchy(OmarchyTheme(104)),
    ThemePreset::Omarchy(OmarchyTheme(105)),
    ThemePreset::Omarchy(OmarchyTheme(106)),
    ThemePreset::Omarchy(OmarchyTheme(107)),
    ThemePreset::Omarchy(OmarchyTheme(108)),
    ThemePreset::Omarchy(OmarchyTheme(109)),
    ThemePreset::Omarchy(OmarchyTheme(110)),
    ThemePreset::Omarchy(OmarchyTheme(111)),
    ThemePreset::Omarchy(OmarchyTheme(112)),
    ThemePreset::Omarchy(OmarchyTheme(113)),
    ThemePreset::Omarchy(OmarchyTheme(114)),
    ThemePreset::Omarchy(OmarchyTheme(115)),
    ThemePreset::Omarchy(OmarchyTheme(116)),
    ThemePreset::Omarchy(OmarchyTheme(117)),
    ThemePreset::Omarchy(OmarchyTheme(118)),
    ThemePreset::Omarchy(OmarchyTheme(119)),
    ThemePreset::Omarchy(OmarchyTheme(120)),
    ThemePreset::Omarchy(OmarchyTheme(121)),
    ThemePreset::Omarchy(OmarchyTheme(122)),
    ThemePreset::Omarchy(OmarchyTheme(123)),
    ThemePreset::Omarchy(OmarchyTheme(124)),
    ThemePreset::Omarchy(OmarchyTheme(125)),
    ThemePreset::Omarchy(OmarchyTheme(126)),
    ThemePreset::Omarchy(OmarchyTheme(127)),
    ThemePreset::Omarchy(OmarchyTheme(128)),
    ThemePreset::Omarchy(OmarchyTheme(129)),
    ThemePreset::Omarchy(OmarchyTheme(130)),
    ThemePreset::Omarchy(OmarchyTheme(131)),
    ThemePreset::Omarchy(OmarchyTheme(132)),
    ThemePreset::Omarchy(OmarchyTheme(133)),
    ThemePreset::Omarchy(OmarchyTheme(134)),
    ThemePreset::Omarchy(OmarchyTheme(135)),
    ThemePreset::Omarchy(OmarchyTheme(136)),
    ThemePreset::Omarchy(OmarchyTheme(137)),
    ThemePreset::Omarchy(OmarchyTheme(138)),
    ThemePreset::Omarchy(OmarchyTheme(139)),
    ThemePreset::Omarchy(OmarchyTheme(140)),
    ThemePreset::Omarchy(OmarchyTheme(141)),
    ThemePreset::Omarchy(OmarchyTheme(142)),
    ThemePreset::Omarchy(OmarchyTheme(143)),
    ThemePreset::Omarchy(OmarchyTheme(144)),
    ThemePreset::Omarchy(OmarchyTheme(145)),
    ThemePreset::Omarchy(OmarchyTheme(146)),
    ThemePreset::Omarchy(OmarchyTheme(147)),
    ThemePreset::Omarchy(OmarchyTheme(148)),
    ThemePreset::Omarchy(OmarchyTheme(149)),
    ThemePreset::Omarchy(OmarchyTheme(150)),
    ThemePreset::Omarchy(OmarchyTheme(151)),
    ThemePreset::Omarchy(OmarchyTheme(152)),
    ThemePreset::Omarchy(OmarchyTheme(153)),
    ThemePreset::Omarchy(OmarchyTheme(154)),
    ThemePreset::Omarchy(OmarchyTheme(155)),
    ThemePreset::Omarchy(OmarchyTheme(156)),
    ThemePreset::Omarchy(OmarchyTheme(157)),
    ThemePreset::Omarchy(OmarchyTheme(158)),
    ThemePreset::Omarchy(OmarchyTheme(159)),
    ThemePreset::Omarchy(OmarchyTheme(160)),
    ThemePreset::Omarchy(OmarchyTheme(161)),
    ThemePreset::Omarchy(OmarchyTheme(162)),
    ThemePreset::Omarchy(OmarchyTheme(163)),
    ThemePreset::Omarchy(OmarchyTheme(164)),
    ThemePreset::Omarchy(OmarchyTheme(165)),
    ThemePreset::Omarchy(OmarchyTheme(166)),
    ThemePreset::Omarchy(OmarchyTheme(167)),
    ThemePreset::Omarchy(OmarchyTheme(168)),
    ThemePreset::Omarchy(OmarchyTheme(169)),
    ThemePreset::Omarchy(OmarchyTheme(170)),
    ThemePreset::Omarchy(OmarchyTheme(171)),
    ThemePreset::Omarchy(OmarchyTheme(172)),
    ThemePreset::Omarchy(OmarchyTheme(173)),
    ThemePreset::Omarchy(OmarchyTheme(174)),
    ThemePreset::Omarchy(OmarchyTheme(175)),
    ThemePreset::Omarchy(OmarchyTheme(176)),
    ThemePreset::Omarchy(OmarchyTheme(177)),
];
