#!/usr/bin/env python3
"""Generate Uniterm's offline Omarchy catalog from the attributed source snapshot."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tempfile
import tomllib
import urllib.request

HERE = Path(__file__).resolve().parent
OUTPUT = HERE.parents[1] / 'crates/uniterm-core/src/config/omarchy.rs'
BUILTINS = ('UnitermDark UnitermLight Catppuccin TokyoNight Dracula Nord '
            'GruvboxDark GruvboxLight SolarizedDark SolarizedLight Kanagawa RosePine').split()


def color(value):
    if not isinstance(value, str) or not re.fullmatch(r'(?:#|0x)?[0-9a-fA-F]{6}', value):
        raise ValueError(f'Invalid RGB color: {value!r}')
    return int(value.removeprefix('#').removeprefix('0x'), 16)


def blend(background, foreground, percent):
    return sum((((background >> shift & 255) * (100 - percent)
                 + (foreground >> shift & 255) * percent) // 100) << shift
               for shift in (16, 8, 0))


def palette(source):
    raw = source['content']
    if hashlib.sha256(raw.encode()).hexdigest() != source['sha256']:
        raise ValueError(f"Checksum mismatch: {source['name']}")
    data = tomllib.loads(raw)
    if source['path'].endswith('alacritty.toml'):
        colors = data['colors']
        primary, normal = colors['primary'], colors['normal']
        data = dict(background=primary['background'], foreground=primary['foreground'],
                    accent=normal['blue'], muted=colors.get('bright', normal)['black'],
                    green=normal['green'], yellow=normal['yellow'], red=normal['red'])
    bg, fg = color(data['background']), color(data['foreground'])
    surface = color(data['lighter_background']) if 'lighter_background' in data else blend(bg, fg, 8)
    accent = color(data.get('accent', data.get('blue', data.get('color4'))))
    muted = color(data.get('muted', data.get('color8', data['foreground'])))
    # Some monochrome palettes intentionally repeat roles. Ensure chrome remains visible.
    if surface == fg:
        surface = blend(bg, fg, 8)
    if accent == surface:
        accent = fg
    return [bg, surface, fg, muted, accent,
            color(data.get('green', data.get('color2'))),
            color(data.get('yellow', data.get('color3'))),
            color(data.get('red', data.get('color1')))]


def catalog(snapshot):
    result = []
    for source in snapshot['sources']:
        if 'error' in source:
            continue
        slug = re.sub('[^a-z0-9]+', '-', source['name'].lower()).strip('-')
        prefix = {'bundled': 'omarchy-', 'gallery': 'omarchy-community-',
                  'local': 'omarchy-local-', 'local-bundled': 'omarchy-local-'}[source['origin']]
        result.append((prefix + slug, palette(source), source))
    result.sort(key=lambda row: row[0])
    names = [row[0] for row in result]
    if len(names) != len(set(names)):
        raise ValueError('Duplicate theme names')
    return result


def render(rows):
    lines = ['// Generated by themes/omarchy/generate.py; do not edit.',
             '// Source URLs, revisions, checksums and notices: themes/omarchy/sources.json.',
             'use super::{OmarchyTheme, ThemePreset};', '',
             'pub(super) const PALETTES: &[(&str, [u32; 8])] = &[']
    for name, values, _ in rows:
        lines.append(f'    ("{name}", [' + ', '.join(f'0x{x:06x}' for x in values) + ']),')
    lines += ['];', '', 'pub(super) const ALL: &[ThemePreset] = &[']
    lines += [f'    ThemePreset::{name},' for name in BUILTINS]
    lines += [f'    ThemePreset::Omarchy(OmarchyTheme({i})),' for i in range(len(rows))]
    lines += ['];', '']
    with tempfile.TemporaryDirectory(prefix='uniterm-theme-') as directory:
        path = Path(directory) / 'omarchy.rs'
        path.write_text('\n'.join(lines))
        subprocess.run(['rustfmt', '--edition', '2021', str(path)], check=True)
        return path.read_text()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check generated data without writing')
    parser.add_argument('--verify-upstream', action='store_true', help='Verify pinned public source hashes over HTTPS')
    args = parser.parse_args()
    snapshot = json.loads((HERE / 'sources.json').read_text())
    rows = catalog(snapshot)
    if args.verify_upstream:
        for source in snapshot['sources']:
            if 'content' not in source or not source.get('revision'):
                continue
            repo = source['repository'].removesuffix('.git').rstrip('/')
            if not repo.startswith('https://github.com/'):
                continue
            url = repo.replace('github.com', 'raw.githubusercontent.com') + '/' + source['revision'] + '/' + source['path']
            raw = urllib.request.urlopen(url, timeout=30).read()
            if hashlib.sha256(raw).hexdigest() != source['sha256']:
                raise ValueError(f"Upstream differs from captured palette: {url}")
    generated = render(rows)
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit('Generated catalog is stale; run themes/omarchy/generate.py')
    else:
        OUTPUT.write_text(generated)
    print(f'{len(rows)} Omarchy palettes; {len(BUILTINS) + len(rows)} total presets')


if __name__ == '__main__':
    main()
